/**
 * Firebase Cloud Functions — Vantiq CUET Platform
 * TWO-TIER ARCHITECTURE:
 *
 * TIER 1 — QuickPractice (FREE FOREVER)
 * - 15 questions, no timer, rotating question types
 * - Never counted toward freemium limit or daily limit
 * - Labelled "Always Free" — permanent hook to platform
 *
 * TIER 2 — Mock Exam (Free ×4, then ₹199)
 * - 50 questions, 60 min, full NTA simulation
 * - Counts toward freemium limit (4 free) and daily limit (15/day)
 *
 * CACHE: 30 sets per mode × 2 modes = 60 sets total
 * SCHEDULE: Nightly 2AM IST via GitHub Actions cron
 */
const functions = require("firebase-functions");
const admin     = require("firebase-admin");
const axios     = require("axios");
const crypto    = require("crypto");
const Razorpay  = require("razorpay");

admin.initializeApp();
const db               = admin.firestore();
const FREE_LIMIT       = 4;
const UNLOCK_AMOUNT    = 19900;
const CACHE_SIZE       = 120; // increased from 60 — buffer for scale (5k users drain 60 sets in hours)
const CACHE_TTL_MS     = 7 * 24 * 60 * 60 * 1000;
const DAILY_TEST_LIMIT = 15;
const MODES            = ["Mock", "QuickPractice"];  // Mock first — highest priority

// ── CUET Exam Intelligence Layer ──────────────────────────────────────────────
// Researched from official NTA CUET UG papers (2022–2025) and syllabus.
// This constant is the permanent knowledge base that grounds every question
// generated by Claude. It is injected into each batch prompt as a targeted
// contextual brief — zero extra API calls, zero Firestore reads on the hot path.
// To update: trigger updateCuetIntelligence from admin dashboard → deploys via
// GitHub Actions as a code update. Intelligence grows with the platform.
const CUET_EXAM_INTELLIGENCE = {
  version: "1.1",
  lastResearched: "2026-04-10",
  subjects: {
    English_101: {
      officialCode: "101",
      examPattern: {
        totalQuestions: 50, duration: 60,
        marking: { correct: 5, wrong: -1, unanswered: 0 },
      },
      // ── 5-year trend intelligence per topic ──────────────────────────────
      topics: {
        ReadingComprehension: {
          questions: 22, passages: 3,
          passageWordRange: [250, 300],
          passageTypes: ["factual_scientific", "narrative_biographical", "literary_philosophical"],
          questionTypeFrequency: {
            // Based on NTA official papers 2022-2025
            inference:             "35%", // highest — test CUET emphasises inference over recall
            vocabulary_in_context: "20%", // word meaning as used in passage, not dictionary
            specific_detail:       "18%",
            main_idea_or_title:    "12%",
            authors_tone:          "10%", // distinguish analytical / critical / appreciative / neutral
            logical_conclusion:     "5%",
          },
          highFrequencyPassageThemes: [
            // Themes that have appeared in official papers multiple times
            "environmental sustainability and climate action",
            "Indian culture, heritage and civilisation",
            "digital technology and its societal impact",
            "women empowerment and gender equality",
            "scientific discoveries and innovation",
            "social inequality and economic development",
            "mental health and wellbeing in modern life",
            "historical figures and their contributions",
            "education systems and pedagogy",
            "biodiversity and ecological balance",
          ],
          examTrends: [
            "Inference questions outnumber factual recall 3:1 — never ask what the passage explicitly states",
            "Vocabulary-in-context: test how the word functions in the passage, not its dictionary definition",
            "Author tone questions require distinguishing between critically analytical vs appreciative vs neutral",
            "Literary passages (batch 3) often use extended metaphor — questions test figurative comprehension",
            "Passages are contemporary (post-2015 themes) — no archaic Victorian or pre-independence text",
            "No brand names, no living named individuals, no political party names in passages",
            "Title suggestion questions: correct title is specific and captures the central argument, not just the topic",
          ],
          qualityRules: [
            "All 4 options must be plausible for a moderately prepared student — never 3 obviously wrong options",
            "Correct answer must be definitively supported by passage text — no external knowledge required",
            "Distractor options for inference questions must be: partially true but incomplete, or logically adjacent",
          ],
        },
        SynonymsAntonyms: {
          questions: 9,
          difficulty: "B2-C1 CEFR — academic and literary vocabulary",
          examTrends: [
            "Antonym questions appear more than synonym questions (roughly 6:3 ratio historically)",
            "Words tested are frequently drawn from the RC passage vocabulary in the same paper",
            "Academic register: analytical, contemplative, pragmatic, ephemeral, sagacious, benevolent, didactic, verbose, equivocal",
            "Never test words with universally obvious answers (e.g. happy/sad, hot/cold)",
            "Distractors are often words with similar spelling or partial semantic overlap",
          ],
          avoidPatterns: [
            "Archaic or obscure words unknown to any Class 12 student",
            "Technical domain-specific jargon",
            "Words where all 4 options could arguably be synonyms/antonyms",
          ],
        },
        SentenceRearrangement: {
          questions: 7,
          format: "P/Q/R/S jumbled sentences — choose correct sequence from 4 options",
          examTrends: [
            "2022-2023: narrative passages dominated; 2024-2025: shift toward argumentative and expository",
            "Transition words are structural keys: 'however' signals contrast, 'therefore' signals conclusion",
            "Pronoun resolution: pronouns must refer to antecedents in earlier sentences — key for sequencing",
            "Opening sentence establishes the topic or context; closing sentence draws conclusion or implication",
            "P/Q/R/S length: usually 4 sentences, occasionally 5; each sentence is 10-20 words",
          ],
          qualityRules: [
            "Only one sequence must be grammatically and logically correct — no ties between options",
            "Avoid sequences that are ambiguous due to incomplete context",
            "Each sentence should have a clear logical relationship to at least one adjacent sentence",
          ],
        },
        ChoosingCorrectWord: {
          questions: 7,
          format: "Fill in the blank — select most appropriate word from 4 options",
          examTrends: [
            "Collocations are heavily tested: 'make a decision' not 'do a decision', 'take a chance' not 'give a chance'",
            "Preposition precision: 'interested in' vs 'interested at', 'comply with' vs 'comply to'",
            "Academic register: words used in formal writing, not casual conversation",
            "Two options are usually clearly wrong; test the nuance between the two plausible ones",
            "Formal/informal register distinction: selecting formal word in academic context",
          ],
          qualityRules: [
            "Context sentence must provide enough clues to identify the correct word",
            "Correct answer should be determinable without dictionary — test usage intelligence, not memorisation",
          ],
        },
        MatchTheFollowing: {
          questions: 3,
          format: "Column A (word/phrase/idiom) → Column B (meaning/usage/context)",
          examTrends: [
            "Idiom-meaning pairs are most common: 'hit the nail on the head', 'bite the bullet'",
            "Word-usage context: which sentence uses the word correctly",
            "All Column B entries must be plausible matches for at least one Column A item — no obvious leftovers",
          ],
        },
        GrammarVocabulary: {
          questions: 2,
          types: ["error_spotting", "correct_usage"],
          examTrends: [
            "Error spotting: subject-verb agreement, tense consistency, article misuse (a/an/the) are most frequent",
            "Dangling modifiers and incorrect preposition usage appear occasionally",
            "Never plant errors that educated native speakers would debate",
            "One clear unambiguous error per question — no ambiguity in what is wrong",
          ],
        },
      },
      difficultyCalibration: {
        // Calibration ensures questions are neither too easy (no prep value) nor too hard (demoralising)
        overall: "60% easy-moderate, 30% moderate, 10% challenging",
        byTopic: {
          ReadingComprehension: "moderate — inference-heavy, not recall-heavy",
          SynonymsAntonyms:     "moderate-challenging (B2-C1, never trivial)",
          SentenceRearrangement:"moderate (logical sequencing, 1 clear answer)",
          ChoosingCorrectWord:  "easy-moderate (collocations and register)",
          MatchTheFollowing:    "easy-moderate (idioms and phrases)",
          GrammarVocabulary:    "easy (clear errors, unambiguous)",
        },
      },
    },
    // GAT and Economics intelligence will be added here when those subjects launch
  },
};

// Returns a targeted intelligence brief for a specific batch — injected into prompt.
// Designed to be SHORT (~150 tokens) and highly relevant to that batch's content.
// Zero latency: reads from module-level constant, no I/O.
function buildIntelligenceBrief(batchNum) {
  const eng = CUET_EXAM_INTELLIGENCE.subjects.English_101;
  const rc  = eng.topics.ReadingComprehension;
  const sa  = eng.topics.SynonymsAntonyms;
  const sr  = eng.topics.SentenceRearrangement;
  const ccw = eng.topics.ChoosingCorrectWord;
  const mtf = eng.topics.MatchTheFollowing;
  const gv  = eng.topics.GrammarVocabulary;

  if (batchNum === 1 || batchNum === 2 || batchNum === 3) {
    const passageType = ["factual/scientific", "narrative/biographical", "literary/philosophical"][batchNum - 1];
    return `EXAM INTELLIGENCE (NTA CUET English 2022-2025 patterns):
RC passage must be ${passageType}, contemporary (post-2015), 250-300 words. No brand names or named living individuals.
Question type targets: inference (35%), vocabulary-in-context (20%), specific detail (18%), main idea (12%), author tone (10%).
Author tone: distinguish precisely between analytical, critical, appreciative, and neutral — never use vague labels.
Inference questions: answer must follow from passage logic, not be explicitly stated. Avoid "according to the passage" wording.
Vocabulary-in-context: test how the word functions in its specific sentence, not its dictionary definition.
Synonyms/Antonyms: B2-C1 academic vocabulary. Antonyms preferred over pure synonyms. Words should be passage-adjacent.
All 4 options must be genuinely plausible — a prepared student must think, not just eliminate obvious wrong answers.
Difficulty: moderate for RC (inference-heavy), moderate-challenging for vocabulary.`;
  }

  if (batchNum === 4) {
    return `EXAM INTELLIGENCE (NTA CUET English 2022-2025 patterns):
Sentence Rearrangement (2024-2025 trend): argumentative/expository passages, not just narrative.
Structural keys: transition words (however, therefore, moreover, consequently) signal sentence position.
Pronoun resolution: pronoun must refer to antecedent in an earlier sentence — use this to determine sequence.
Opening sentence establishes topic/context; closing sentence draws conclusion or states implication.
Only one sequence must be clearly correct — if two sequences both seem valid, rewrite the sentences.
Grammar/Vocabulary: target subject-verb agreement, tense consistency, article misuse (a/an/the).
Plant one clear, unambiguous error — never an error that educated speakers would debate.
Synonyms/Antonyms (1 question): B2-C1 level, academic register, test nuance not obvious pairs.
Difficulty: moderate for SR, easy for grammar.`;
  }

  if (batchNum === 5) {
    return `EXAM INTELLIGENCE (NTA CUET English 2022-2025 patterns):
Choosing Correct Word: test collocations and register precision, not raw vocabulary.
Common collocation patterns tested: make/take/do + noun, preposition-noun pairs, formal vs informal register.
Two options should be plausible — test the nuance between them. Two options should be clearly wrong.
Context sentence must provide enough clues to arrive at correct answer without a dictionary.
Match the Following: idiom-meaning pairs are most common. All Column B entries must be relevant to at least one Column A item.
Avoid obscure literary device identification. Use idioms and phrases from everyday academic/literary English.
Correct answer should be determinable by a well-prepared Class 12 student.
Difficulty: easy-moderate for both topics.`;
  }

  // QuickPractice brief — general
  return `EXAM INTELLIGENCE (NTA CUET English 101 patterns):
RC passage: contemporary topic (post-2015), 120-150 words for Quick Practice. Inference questions preferred over recall.
Vocabulary: B2 level — accessible but not trivial. Test contextual usage.
All 4 options must be plausible. Difficulty: accessible — suitable for first-time platform visitors.
Explanations must state why the correct answer is right AND why the top distractor is wrong.`;
}


function todayIST() {
  return new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" });
}

function setCORS(res) {
  res.set("Access-Control-Allow-Origin",  "*");
  res.set("Access-Control-Allow-Methods", "POST, GET, OPTIONS");
  res.set("Access-Control-Allow-Headers", "Content-Type, Authorization, x-admin-key");
  res.set("Access-Control-Max-Age", "3600");
}

// Restrictive CORS for payment endpoints — only accept requests from the platform origin
// Wildcard CORS on verifyPayment and createOrder is a security anti-pattern
const ALLOWED_ORIGINS = [
  "https://vantiq-cuetmock.netlify.app",
  "http://localhost:5173", // local dev
  "http://localhost:4173", // vite preview
];
function setPaymentCORS(req, res) {
  const origin = req.headers.origin || "";
  const allowed = ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  res.set("Access-Control-Allow-Origin",  allowed);
  res.set("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.set("Access-Control-Allow-Headers", "Content-Type, Authorization");
  res.set("Access-Control-Max-Age", "3600");
  res.set("Vary", "Origin");
}

async function verifyToken(req, res) {
  const h = req.headers.authorization || "";
  if (!h.startsWith("Bearer ")) { res.status(401).json({ error: "Unauthorized" }); return null; }
  try { return await admin.auth().verifyIdToken(h.split("Bearer ")[1]); }
  catch (e) { res.status(401).json({ error: "Invalid token" }); return null; }
}

function extractJSON(rawText) {
  let cleaned = rawText.replace(/```json\s*/gi, "").replace(/```\s*/gi, "").trim();
  const firstBrace   = cleaned.indexOf("{");
  const firstBracket = cleaned.indexOf("[");
  if (firstBrace !== -1 && (firstBracket === -1 || firstBrace < firstBracket)) {
    const end = cleaned.lastIndexOf("}");
    if (end > firstBrace) cleaned = cleaned.substring(firstBrace, end + 1);
  } else if (firstBracket !== -1) {
    const end = cleaned.lastIndexOf("]");
    if (end > firstBracket) cleaned = cleaned.substring(firstBracket, end + 1);
  }
  try { return JSON.parse(cleaned); } catch (e1) {}
  const fixed = cleaned.replace(/,\s*([}\]])/g, "$1");
  try { return JSON.parse(fixed); } catch (e2) {}
  functions.logger.error("JSON_EXTRACT_FAILED", { raw_preview: rawText.substring(0, 300) });
  throw new Error("JSON extraction failed");
}

async function callAnthropic(prompt, maxTokens, apiKey) {
  const r = await axios.post(
    "https://api.anthropic.com/v1/messages",
    { model: "claude-haiku-4-5-20251001", max_tokens: maxTokens, messages: [{ role: "user", content: prompt }] },
    { headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" }, timeout: 105000 }
  );
  if (r.data?.stop_reason === "max_tokens") throw new Error("TRUNCATION");
  const parsed = extractJSON(r.data?.content?.[0]?.text || "");
  return parsed.questions || parsed;
}

function buildPrompt(mode) {
  if (mode === "QuickPractice") {
    return `You are an NTA CUET English (101) question generator.
` + buildIntelligenceBrief("QuickPractice") + `
Generate exactly 15 MCQ questions for a quick practice session. Return ONLY a JSON object — no markdown, no preamble.

JSON schema:
{"questions":[{"question":"...","options":["A","B","C","D"],"correct":0,"topic":"Reading Comprehension","passage":"short passage text or null","explanation":"1-2 sentences"}]}

Topic distribution (MANDATORY — exactly these counts):
- Reading Comprehension: 5 questions (1 short passage, 120-150 words, factual or narrative)
- Synonyms and Antonyms: 3 questions (passage = null)
- Sentence Rearrangement: 3 questions (passage = null)
- Choosing Correct Word: 2 questions (passage = null)
- Grammar and Vocabulary: 2 questions (passage = null)

Rules:
1. correct is 0-indexed (0=A,1=B,2=C,3=D)
2. All RC questions must share identical passage text
3. Every question must have exactly 4 options
4. Every question must have an explanation
5. Difficulty: accessible — suitable for first-time platform visitors
6. Return ONLY the JSON object. Begin with { — nothing before it.`;
  }
  return null;
}

// ── 5-batch Mock generation (10 questions each = exactly 50 total) ─────────────
// Each batch is small enough to return exactly 10 reliably
function buildMockBatch(batchNum) {
  const schema = '{"questions":[{"question":"...","options":["A","B","C","D"],"correct":0,"topic":"...","passage":"passage text or null","explanation":"2-3 sentences"}]}';

  // Each batch requests 12 questions (buffer) — sliced to exactly 10 after validation
  // Requesting 12 makes it very reliable to get >= 10 valid questions
  // Passage-based batches (1-3): all questions in a batch share ONE passage → no mixing
  const batches = {
    1: `You are an NTA CUET English (101) question paper generator.
` + buildIntelligenceBrief(1) + `
Generate exactly 12 MCQ questions. Return ONLY a JSON object — no markdown, no preamble.
JSON schema: ${schema}
Topic distribution (MANDATORY):
- Reading Comprehension: 8 questions — write ONE factual passage (science/geography/history, exactly 250-300 words). All 8 RC questions must use IDENTICAL passage text.
- Synonyms and Antonyms: 4 questions (passage = null)
Rules: correct is 0-indexed (0=A,1=B,2=C,3=D). Difficulty: challenging — NTA exam standard. Explanation: 2-3 sentences.
Return ONLY the JSON object. Begin with { — nothing before it.`,

    2: `You are an NTA CUET English (101) question paper generator.
` + buildIntelligenceBrief(2) + `
Generate exactly 12 MCQ questions. Return ONLY a JSON object — no markdown, no preamble.
JSON schema: ${schema}
Topic distribution (MANDATORY):
- Reading Comprehension: 9 questions — write ONE narrative passage (story or biographical excerpt, exactly 250-300 words). All 9 RC questions must use IDENTICAL passage text.
- Synonyms and Antonyms: 3 questions (passage = null)
Rules: correct is 0-indexed (0=A,1=B,2=C,3=D). Difficulty: challenging — NTA exam standard. Explanation: 2-3 sentences.
Return ONLY the JSON object. Begin with { — nothing before it.`,

    3: `You are an NTA CUET English (101) question paper generator.
` + buildIntelligenceBrief(3) + `
Generate exactly 12 MCQ questions. Return ONLY a JSON object — no markdown, no preamble.
JSON schema: ${schema}
Topic distribution (MANDATORY):
- Reading Comprehension: 8 questions — write ONE literary/philosophical passage (critical prose, exactly 250-300 words). All 8 RC questions must use IDENTICAL passage text.
- Synonyms and Antonyms: 4 questions (passage = null)
Rules: correct is 0-indexed (0=A,1=B,2=C,3=D). Difficulty: challenging — NTA exam standard. Explanation: 2-3 sentences.
Return ONLY the JSON object. Begin with { — nothing before it.`,

    4: `You are an NTA CUET English (101) question paper generator.
` + buildIntelligenceBrief(4) + `
Generate exactly 12 MCQ questions. Return ONLY a JSON object — no markdown, no preamble.
JSON schema: ${schema}
Topic distribution (MANDATORY):
- Sentence Rearrangement: 8 questions — jumbled P/Q/R/S format, arrange in logical order (passage = null)
- Grammar and Vocabulary: 3 questions — error spotting or correct usage (passage = null)
- Synonyms and Antonyms: 1 question (passage = null)
Rules: correct is 0-indexed (0=A,1=B,2=C,3=D). Difficulty: challenging — NTA exam standard. Explanation: 2-3 sentences.
Return ONLY the JSON object. Begin with { — nothing before it.`,

    5: `You are an NTA CUET English (101) question paper generator.
` + buildIntelligenceBrief(5) + `
Generate exactly 12 MCQ questions. Return ONLY a JSON object — no markdown, no preamble.
JSON schema: ${schema}
Topic distribution (MANDATORY):
- Choosing Correct Word: 8 questions — fill in the blank or cloze (passage = null)
- Match the Following: 4 questions — word-meaning or phrase pairs (passage = null)
Rules: correct is 0-indexed (0=A,1=B,2=C,3=D). Difficulty: challenging — NTA exam standard. Explanation: 2-3 sentences.
Return ONLY the JSON object. Begin with { — nothing before it.`,
  };

  return batches[batchNum];
}

// ── Quality Gate — validates every question before accepting the set ──────────
function validateQuestionSet(questions, mode) {
  // With 5-batch architecture, Mock always returns exactly 50 (5 × 10)
  const REQUIRED_COUNT = mode === "Mock" ? 50 : 15;
  const errors = [];

  if (questions.length !== REQUIRED_COUNT) {
    errors.push(`COUNT:${questions.length}/${REQUIRED_COUNT} — must be exactly ${REQUIRED_COUNT}`);
  }

  questions.forEach((q, i) => {
    const n = i + 1;
    if (!q.question || typeof q.question !== "string" || q.question.trim().length < 10) {
      errors.push(`Q${n}:MISSING_QUESTION`);
    }
    if (!Array.isArray(q.options) || q.options.length !== 4) {
      errors.push(`Q${n}:OPTIONS_COUNT(${q.options?.length ?? 0})`);
    }
    if (q.options) {
      q.options.forEach((opt, j) => {
        if (!opt || typeof opt !== "string" || opt.trim().length === 0) {
          errors.push(`Q${n}:EMPTY_OPTION_${j}`);
        }
      });
    }
    if (typeof q.correct !== "number" || q.correct < 0 || q.correct > 3) {
      errors.push(`Q${n}:INVALID_CORRECT(${q.correct})`);
    }
    if (!q.topic || typeof q.topic !== "string") {
      errors.push(`Q${n}:MISSING_TOPIC`);
    }
    if (!q.explanation || typeof q.explanation !== "string" || q.explanation.trim().length < 10) {
      errors.push(`Q${n}:MISSING_EXPLANATION`);
    }
  });

  return errors;
}

async function generateQuestionSet(mode, apiKey) {
  const MAX_RETRIES = 2; // 3 total attempts
  let lastError;

  for (let attempt = 1; attempt <= MAX_RETRIES + 1; attempt++) {
    try {
      let questions;

      if (mode === "QuickPractice") {
        const prompt = buildPrompt("QuickPractice");
        questions = await callAnthropic(prompt, 5000, apiKey);
      } else {
        // 5 sequential batches of 10 questions each = exactly 50
        // Per-batch retry strategy: retry individual failing batch (not all 5)
        // Slice to exactly 10 if model returns more
        // RC batches (1-3) embed full passage text in every question's JSON field:
        // 9 RC questions × ~350 tokens/passage = ~3150 tokens in passages alone.
        // 4000 was causing TRUNCATION on batches 1-3 every single attempt.
        // 8000 provides safe headroom: ~4650 token worst-case (batch 2) fits comfortably.
        const tokenBudgets = [8000, 8000, 8000, 3000, 3000]; // RC batches need 8000 — passage repeats in every question
        const allBatches = [];

        for (let b = 1; b <= 5; b++) {
          let batchResult = null;
          let batchError = null;

          // Up to 3 attempts per individual batch
          for (let ba = 1; ba <= 3; ba++) {
            try {
              functions.logger.info("BATCH_START", { batchNum: b, attempt: ba, tokenBudget: tokenBudgets[b-1] });
              const raw = await callAnthropic(buildMockBatch(b), tokenBudgets[b-1], apiKey);
              const count = Array.isArray(raw) ? raw.length : 0;
              functions.logger.info("BATCH_RESULT", { batchNum: b, attempt: ba, count });

              if (!Array.isArray(raw) || count < 10) {
                // Need >= 10 to slice to exactly 10 — retry this batch alone
                throw new Error(`BATCH_${b}_LOW:${count}/12`);
              }
              // Slice to exactly 10 — drop the 2 buffer questions
              batchResult = raw.slice(0, 10);
              functions.logger.info("BATCH_ACCEPTED", { batchNum: b, generated: count, used: 10 });
              break; // Batch succeeded
            } catch(e) {
              batchError = e;
              functions.logger.warn("BATCH_RETRY", { batchNum: b, attempt: ba, reason: e.message });
              if (ba < 3) await new Promise(r => setTimeout(r, 1500 * ba));
            }
          }

          if (!batchResult) {
            throw new Error(`BATCH_${b}_FAILED_ALL_ATTEMPTS: ${batchError?.message}`);
          }
          allBatches.push(...batchResult);
          await new Promise(r => setTimeout(r, 800));
        }

        // Final count check — should be exactly 50
        if (allBatches.length !== 50) {
          throw new Error(`COMBINED_COUNT:${allBatches.length}/50`);
        }
        questions = allBatches;
      }

      // ── Normalise fields before quality gate ────────────────────────────────
      // Haiku occasionally returns correct as a string ("0", "A") instead of number.
      // Coerce here so validateQuestionSet's typeof check never blocks a valid set.
      questions = questions.map(q => ({
        ...q,
        correct: typeof q.correct === "string"
          ? (["A","B","C","D"].includes(q.correct.toUpperCase())
              ? ["A","B","C","D"].indexOf(q.correct.toUpperCase())
              : parseInt(q.correct, 10))
          : q.correct,
        explanation: (q.explanation || "").trim() || "",
      }));

      // ── Quality gate ────────────────────────────────────────────────────────
      const errors = validateQuestionSet(questions, mode);
      if (errors.length > 0) {
        const errorSummary = errors.slice(0, 5).join(", ") + (errors.length > 5 ? `... +${errors.length - 5} more` : "");
        functions.logger.warn("QUALITY_GATE_FAILED", { mode, attempt, count: questions.length, errors: errorSummary });
        throw new Error(`QUALITY_FAIL:${errorSummary}`);
      }

      functions.logger.info("QUALITY_GATE_PASSED", { mode, attempt, count: questions.length });
      return questions;

    } catch (e) {
      lastError = e;
      if (attempt <= MAX_RETRIES) {
        functions.logger.warn("GENERATION_RETRY", { mode, attempt, reason: e.message });
        await new Promise(r => setTimeout(r, 2000 * attempt)); // backoff: 2s, 4s
      }
    }
  }

  // All attempts failed
  throw new Error(`GENERATION_FAILED_AFTER_${MAX_RETRIES + 1}_ATTEMPTS: ${lastError?.message}`);
}

// ─── MANUAL/SCHEDULED CACHE TRIGGER ─────────────────────────────────────────
exports.triggerCacheWarm = functions
  .runWith({ timeoutSeconds: 540, memory: "512MB" })
  .https.onRequest(async (req, res) => {
    setCORS(res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }
    try {
      // Accept key from body (browser-safe, no CORS preflight) or header (curl)
      const adminKey    = req.body?.adminKey || req.headers["x-admin-key"] || "";
      const cfg         = functions.config();
      const expectedKey = cfg.admin?.key || process.env.ADMIN_KEY || "";
      if (!adminKey || adminKey !== expectedKey) {
        res.status(403).json({ error: "Forbidden" }); return;
      }
      const KEY = cfg.anthropic?.api_key || process.env.ANTHROPIC_API_KEY;
      if (!KEY) { res.status(500).json({ error: "No API key configured" }); return; }
      const cutoff = new Date(Date.now() - CACHE_TTL_MS);
      // Optional targeted mode — pass {"mode":"Mock"} to fill only Mock
      const targetMode = req.body && req.body.mode ? req.body.mode : null;
      const clearMode  = req.body && req.body.clear === true;
      const modesToFill = (targetMode && MODES.includes(targetMode)) ? [targetMode] : MODES;

      // If clear:true, delete all existing docs for targeted modes before filling
      if (clearMode && targetMode) {
        const toDelete = await db.collection("questionCache").where("mode", "==", targetMode).get();
        const delBatch = db.batch();
        toDelete.docs.forEach(d => delBatch.delete(d.ref));
        await delBatch.commit();
        functions.logger.info("CACHE_CLEARED", { mode: targetMode, deleted: toDelete.size });
      }

      const status = {};
      for (const mode of MODES) {
        const snap  = await db.collection("questionCache").where("mode", "==", mode).get();
        const fresh = snap.docs.filter(d => d.data().createdAt?.toDate() > cutoff);
        status[mode] = { current: fresh.length, needed: Math.max(0, CACHE_SIZE - fresh.length) };
      }
      // Respond immediately — Firebase Gen1 continues executing after res.send()
      // for the full function timeout (540s). Previously, responding only after generation
      // caused curl to time out and disconnect, potentially killing the function before
      // any sets were stored. Immediate response fixes this permanently.
      functions.logger.info("CACHE_WARM_START", { modesToFill, targetMode, status });
      res.status(200).json({
        message: "Cache warming started — generating sets in background",
        status,
        startedAt: new Date().toISOString(),
      });

      // Generation continues AFTER response — function runs until complete or 540s timeout
      const warmStart = Date.now();
      const TIME_BUDGET_MS = 480000; // 8 min — leaves 1 min buffer before 540s timeout
      let generated = 0;
      let skipped = 0;

      try {
        for (const mode of modesToFill) {
          const snap  = await db.collection("questionCache").where("mode", "==", mode).get();
          const fresh = snap.docs.filter(d => d.data().createdAt?.toDate() > cutoff);
          const needed = Math.max(0, CACHE_SIZE - fresh.length);
          functions.logger.info("CACHE_MODE_STATUS", { mode, current: fresh.length, needed });

          let consecutiveFails = 0;
          for (let i = 0; i < needed; i++) {
            if (Date.now() - warmStart > TIME_BUDGET_MS) {
              skipped = needed - i;
              functions.logger.info("CACHE_BUDGET_EXCEEDED", { mode, skipped });
              break;
            }
            if (consecutiveFails >= 5) {
              functions.logger.error("CACHE_MODE_ABANDONED", { mode, reason: "5 consecutive failures — moving to next mode" });
              skipped += needed - i;
              break;
            }
            try {
              const questions = await generateQuestionSet(mode, KEY);
              await db.collection("questionCache").add({
                mode, questions,
                createdAt: admin.firestore.FieldValue.serverTimestamp(),
                questionCount: questions.length,
              });
              generated++;
              consecutiveFails = 0;
              functions.logger.info("CACHE_SET_STORED", { mode, set: i + 1, total: generated, count: questions.length });
              await new Promise(r => setTimeout(r, 2000)); // 2s between sets
            } catch (e) {
              consecutiveFails++;
              functions.logger.error("CACHE_SET_FAILED", { mode, set: i + 1, consecutiveFails, error: e.message });
            }
          }
        }
        functions.logger.info("CACHE_WARM_DONE", { generated, skipped, durationMs: Date.now() - warmStart });
      } catch (e) {
        functions.logger.error("TRIGGER_CACHE_CRASHED", { error: e.message });
      }
    } catch (e) {
      // Outer catch — handles auth/key/status-check failures before res.send() is called
      functions.logger.error("TRIGGER_CACHE_INIT_FAILED", { error: e.message });
      if (!res.headersSent) res.status(500).json({ error: "Function error: " + e.message });
    }
  });

// ─── 1. generateQuestions ────────────────────────────────────────────────────
exports.generateQuestions = functions
  .runWith({ timeoutSeconds: 60, memory: "256MB" }) // raised from 30s — cold start + Firestore reads can exceed 30s
  .https.onRequest(async (req, res) => {
    setCORS(res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }
    if (req.method !== "POST")    { res.status(405).json({ error: "Method not allowed" }); return; }
    const startTime = Date.now();
    const decoded   = await verifyToken(req, res);
    if (!decoded) return;
    const uid = decoded.uid;
    let userDoc;
    try {
      const snap = await db.collection("users").doc(uid).get();
      userDoc    = snap.data() || {};
    } catch (e) { res.status(500).json({ error: "Could not verify access. Please try again." }); return; }

    const mode = (req.body.config || {}).mode || "Mock";

    // QuickPractice: free forever, no limits checked
    if (mode !== "QuickPractice") {
      const isUnlocked = !!(userDoc.unlocked);
      const testsUsed  = userDoc.testsUsed || 0;
      if (!isUnlocked && testsUsed >= FREE_LIMIT) {
        res.status(402).json({ error: "free_limit_reached", paywall: true }); return;
      }
      if (isUnlocked) {
        const today      = todayIST();
        const dailyCount = (userDoc.dailyTests || {})[today] || 0;
        if (dailyCount >= DAILY_TEST_LIMIT) {
          res.status(429).json({ error: "Don't stress yourself too much today. Attempt more tests tomorrow.", code: "daily_limit_reached" }); return;
        }
      }
    }

    const usedSetIds = userDoc.usedCacheSetIds || [];
    const cutoff     = new Date(Date.now() - CACHE_TTL_MS);
    functions.logger.info("GENERATION_START", { uid, mode, usedCount: usedSetIds.length });

    let cacheDoc = null;
    try {
      const allSnap   = await db.collection("questionCache").where("mode", "==", mode).get();
      const usedSet   = new Set(usedSetIds);
      // Quality filter — reject any cached set with fewer than expected questions
      const REQUIRED_Q = mode === "Mock" ? 50 : 15;
      const available = allSnap.docs.filter(d => {
        if (usedSet.has(d.id)) return false;
        if (d.data().createdAt?.toDate() <= cutoff) return false;
        const count = d.data().questionCount || (d.data().questions?.length ?? 0);
        if (count !== REQUIRED_Q) {
          functions.logger.warn("CACHE_SET_SUBSTANDARD", { id: d.id, mode, count, required: REQUIRED_Q });
          return false;
        }
        return true;
      });
      if (available.length > 0) cacheDoc = available[Math.floor(Math.random() * available.length)];
    } catch (e) {
      functions.logger.error("CACHE_QUERY_FAILED", { uid, error: e.message });
      res.status(500).json({ error: "Could not load your test. Please try again." }); return;
    }

    if (!cacheDoc) {
      functions.logger.info("CACHE_EXHAUSTED_FOR_USER", { uid, mode });
      res.status(503).json({
        error: mode === "QuickPractice"
          ? "Quick Practice is being refreshed. Please try again in a few minutes."
          : "You have completed all available tests for this mode. More tests are being prepared — please check back later.",
        code: "no_tests_available"
      }); return;
    }

    const questions = cacheDoc.data().questions;
    const setId     = cacheDoc.id;
    const today     = todayIST();

    // Only increment counters for Mock (not QuickPractice)
    // Use set() with merge:true — works even if user doc doesn't exist yet
    try {
      if (mode === "QuickPractice") {
        await db.collection("users").doc(uid).set({
          lastTestAt: admin.firestore.FieldValue.serverTimestamp(),
          usedCacheSetIds: admin.firestore.FieldValue.arrayUnion(setId),
        }, { merge: true });
      } else {
        await db.collection("users").doc(uid).set({
          testsUsed: admin.firestore.FieldValue.increment(1),
          lastTestAt: admin.firestore.FieldValue.serverTimestamp(),
          usedCacheSetIds: admin.firestore.FieldValue.arrayUnion(setId),
          [`dailyTests.${today}`]: admin.firestore.FieldValue.increment(1),
        }, { merge: true });
      }
    } catch (e) { functions.logger.error("COUNTER_UPDATE_FAIL", { uid, error: e.message }); }

    functions.logger.info("GENERATION_COMPLETE", { uid, mode, setId, source: "cache", questionCount: questions.length, durationMs: Date.now() - startTime });
    res.status(200).json({ questions });
  });

// ─── 2. generateAdvisory ─────────────────────────────────────────────────────
exports.generateAdvisory = functions.runWith({ timeoutSeconds: 60, memory: "128MB" }).https.onRequest(async (req, res) => {
  setCORS(res);
  if (req.method === "OPTIONS") { res.status(204).send(""); return; }
  if (req.method !== "POST")    { res.status(405).json({ error: "Method not allowed" }); return; }
  const decoded = await verifyToken(req, res); if (!decoded) return;
  const { prompt } = req.body;
  const KEY = functions.config().anthropic?.api_key || process.env.ANTHROPIC_API_KEY;
  try {
    const r = await axios.post("https://api.anthropic.com/v1/messages",
      { model: "claude-sonnet-4-6", max_tokens: 500, messages: [{ role: "user", content: prompt }] },
      { headers: { "Content-Type": "application/json", "x-api-key": KEY, "anthropic-version": "2023-06-01" }, timeout: 55000 });
    res.status(200).json({ text: r.data?.content?.[0]?.text || "Keep practising — consistency is key." });
  } catch (e) { res.status(200).json({ text: "Analysis unavailable. Focus on weak topics before next test." }); }
});

// ─── 3. checkTestLimit ───────────────────────────────────────────────────────
exports.checkTestLimit = functions.runWith({ timeoutSeconds: 20, memory: "256MB" }).https.onRequest(async (req, res) => {
  setCORS(res);
  if (req.method === "OPTIONS") { res.status(204).send(""); return; }
  if (req.method !== "POST")    { res.status(405).json({ error: "Method not allowed" }); return; }
  const decoded = await verifyToken(req, res); if (!decoded) return;
  const uid = decoded.uid;
  try {
    const snap       = await db.collection("users").doc(uid).get();
    const ud         = snap.data() || {};
    const isUnlocked = !!(ud.unlocked);
    const testsUsed  = ud.testsUsed || 0;
    const today      = todayIST();
    const dailyCount = (ud.dailyTests || {})[today] || 0;
    const freemiumBlocked = !isUnlocked && testsUsed >= FREE_LIMIT;
    const dailyBlocked    = isUnlocked && dailyCount >= DAILY_TEST_LIMIT;
    const allowed         = !freemiumBlocked && !dailyBlocked;
    const testsRemaining  = isUnlocked ? Math.max(0, DAILY_TEST_LIMIT - dailyCount) : Math.max(0, FREE_LIMIT - testsUsed);
    const limitLabel      = isUnlocked ? `${testsRemaining} mock tests remaining today` : `${testsRemaining} free mock tests remaining`;
    res.status(200).json({
      allowed, isUnlocked, testsUsed,
      freeLimit: FREE_LIMIT,
      freeRemaining: isUnlocked ? null : Math.max(0, FREE_LIMIT - testsUsed),
      dailyLimit: DAILY_TEST_LIMIT,
      dailyCount,
      dailyRemaining: isUnlocked ? Math.max(0, DAILY_TEST_LIMIT - dailyCount) : null,
      testsRemaining, limitLabel,
      quickPracticeAlwaysFree: true,
    });
  } catch (e) { res.status(500).json({ error: "Limit check failed" }); }
});

// ─── 4. createOrder ──────────────────────────────────────────────────────────
exports.createOrder = functions.runWith({ timeoutSeconds: 30, memory: "128MB" }).https.onRequest(async (req, res) => {
  setPaymentCORS(req, res);
  if (req.method === "OPTIONS") { res.status(204).send(""); return; }
  if (req.method !== "POST")    { res.status(405).json({ error: "Method not allowed" }); return; }
  const decoded = await verifyToken(req, res); if (!decoded) return;
  const KID = functions.config().razorpay?.key_id || process.env.RAZORPAY_KEY_ID;
  const SEC = functions.config().razorpay?.secret  || process.env.RAZORPAY_SECRET;
  if (!KID || !SEC) { res.status(500).json({ error: "Payment service not configured" }); return; }
  try {
    const rzp   = new Razorpay({ key_id: KID, key_secret: SEC });
    const order = await rzp.orders.create({ amount: UNLOCK_AMOUNT, currency: "INR", notes: { uid: decoded.uid, product: "cuet_unlimited" } });
    res.status(200).json({ id: order.id, amount: order.amount, currency: order.currency });
  } catch (e) { functions.logger.error("Order fail:", e); res.status(500).json({ error: "Could not create order. Try again." }); }
});

// ─── 5. verifyPayment ────────────────────────────────────────────────────────
exports.verifyPayment = functions.runWith({ timeoutSeconds: 30, memory: "128MB" }).https.onRequest(async (req, res) => {
  setPaymentCORS(req, res);
  if (req.method === "OPTIONS") { res.status(204).send(""); return; }
  if (req.method !== "POST")    { res.status(405).json({ error: "Method not allowed" }); return; }
  const decoded = await verifyToken(req, res); if (!decoded) return;
  const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;
  if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) { res.status(400).json({ error: "Missing payment params" }); return; }
  const SEC = functions.config().razorpay?.secret || process.env.RAZORPAY_SECRET;
  if (!SEC) { res.status(500).json({ error: "Payment service not configured" }); return; }
  const expected = crypto.createHmac("sha256", SEC).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest("hex");
  if (expected !== razorpay_signature) { functions.logger.warn("Sig mismatch uid:", decoded.uid); res.status(400).json({ error: "Signature verification failed", unlocked: false }); return; }
  try {
    // set() with merge:true — safe even if user doc doesn't exist yet (edge case: payment before first login)
    // update() would throw "No document to update" and user would be charged but never unlocked
    await db.collection("users").doc(decoded.uid).set({
      unlocked: true,
      paymentId: razorpay_payment_id,
      orderId: razorpay_order_id,
      unlockedAt: admin.firestore.FieldValue.serverTimestamp(),
    }, { merge: true });
    await db.collection("payments").add({ uid: decoded.uid, orderId: razorpay_order_id, paymentId: razorpay_payment_id, amount: UNLOCK_AMOUNT, status: "verified", createdAt: admin.firestore.FieldValue.serverTimestamp() });
    functions.logger.info("Unlocked uid:", decoded.uid);
    res.status(200).json({ unlocked: true });
  } catch (e) { functions.logger.error("Firestore unlock fail:", e); res.status(500).json({ error: "Unlock failed. Contact support: " + razorpay_payment_id, unlocked: false }); }
});

// ─── 6. razorpayWebhook ──────────────────────────────────────────────────────
exports.razorpayWebhook = functions.runWith({ timeoutSeconds: 30, memory: "128MB" }).https.onRequest(async (req, res) => {
  if (req.method !== "POST") { res.status(405).send("Not allowed"); return; }
  const WS  = functions.config().razorpay?.webhook_secret || process.env.RAZORPAY_WEBHOOK_SECRET;
  if (!WS)  { res.status(500).send("Not configured"); return; }
  const sig = req.headers["x-razorpay-signature"];
  const exp = crypto.createHmac("sha256", WS).update(JSON.stringify(req.body)).digest("hex");
  if (sig !== exp) { functions.logger.warn("Webhook sig mismatch"); res.status(400).send("Invalid signature"); return; }
  const event   = req.body.event;
  const payment = req.body.payload?.payment?.entity;
  if (event === "payment.captured" && payment?.notes?.uid) {
    try { await db.collection("users").doc(payment.notes.uid).update({ unlocked: true, unlockedAt: admin.firestore.FieldValue.serverTimestamp() }); }
    catch (e) { functions.logger.error("Webhook unlock fail:", e); }
  }
  res.status(200).json({ status: "ok" });
});

// ─── 7. generateFeedbackInsights ────────────────────────────────────────────
// Reads all feedback from Firestore, sends to Claude, returns top 3 actionable insights
exports.generateFeedbackInsights = functions
  .runWith({ timeoutSeconds: 60, memory: "256MB" })
  .https.onRequest(async (req, res) => {
    setCORS(res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }

    const adminKey    = req.body?.adminKey || req.headers["x-admin-key"] || "";
    const cfg         = functions.config();
    const expectedKey = cfg.admin?.key || process.env.ADMIN_KEY || "";

    if (!adminKey || adminKey !== expectedKey) {
      res.status(403).json({ error: "Forbidden" }); return;
    }

    const KEY = cfg.anthropic?.api_key || process.env.ANTHROPIC_API_KEY;
    if (!KEY) { res.status(500).json({ error: "API key not configured" }); return; }

    try {
      // Fetch all feedback from Firestore
      const snap = await db.collection("feedback").orderBy("createdAt", "desc").limit(100).get();

      if (snap.empty) {
        res.status(200).json({ insights: [], message: "No feedback yet — insights will appear once users submit feedback." });
        return;
      }

      // Build feedback list for prompt
      const feedbackList = snap.docs.map((d, i) => {
        const data = d.data();
        const date = data.createdAt?.toDate?.()?.toLocaleDateString("en-IN") || "unknown date";
        return `[${i + 1}] ${data.email || "anonymous"} (${date}): ${data.text}`;
      }).join("\n");

      const prompt = `You are a product improvement analyst for Vantiq CUET — an NTA-standard mock test platform for Indian 12th-grade students preparing for CUET 2026 (English subject).

Here is ALL user feedback submitted so far:

${feedbackList}

Analyze this feedback and return ONLY a JSON object with exactly 3 actionable insights. Each insight must:
- Be grounded in what multiple users are pointing to (or a critical single-user signal)
- Name the specific problem area
- Give one concrete fix the product team can implement
- Note the tone (frustrated / confused / positive / neutral)

JSON schema (return ONLY this, no markdown, no preamble):
{
  "insights": [
    {
      "rank": 1,
      "title": "Short title (5-7 words)",
      "theme": "What users are pointing to",
      "signal": "Specific quotes or patterns from the feedback",
      "action": "One concrete thing to fix or improve",
      "tone": "frustrated | confused | positive | mixed",
      "frequency": "X of Y users mention this"
    }
  ],
  "summary": "One sentence overall assessment of where the platform stands based on feedback",
  "generatedAt": "${new Date().toISOString()}"
}

Return ONLY the JSON object. Begin with { — nothing before it.`;

      const r = await axios.post(
        "https://api.anthropic.com/v1/messages",
        {
          model: "claude-haiku-4-5-20251001",
          max_tokens: 1500,
          messages: [{ role: "user", content: prompt }],
        },
        {
          headers: { "Content-Type": "application/json", "x-api-key": KEY, "anthropic-version": "2023-06-01" },
          timeout: 50000,
        }
      );

      const result = extractJSON(r.data?.content?.[0]?.text || "");
      functions.logger.info("INSIGHTS_GENERATED", { count: result?.insights?.length });
      res.status(200).json(result);

    } catch (e) {
      functions.logger.error("INSIGHTS_FAILED", { error: e.message });
      res.status(500).json({ error: "Could not generate insights. Try again." });
    }
  });


// ─── 10. updateCuetIntelligence ──────────────────────────────────────────────
// Refreshes the CUET exam intelligence document using Claude Sonnet.
// Called from admin dashboard "Refresh Intelligence" button or monthly cron.
// Stores updated intelligence in Firestore cuetIntelligence collection.
// Does NOT modify the running functions — intelligence update deploys as code.
// NEVER runs on the student-facing hot path.
exports.updateCuetIntelligence = functions
  .runWith({ timeoutSeconds: 120, memory: "256MB" })
  .https.onRequest(async (req, res) => {
    setCORS(res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }

    const adminKey    = req.body?.adminKey || req.headers["x-admin-key"] || "";
    const cfg         = functions.config();
    const expectedKey = cfg.admin?.key || process.env.ADMIN_KEY || "";
    if (!adminKey || adminKey !== expectedKey) {
      res.status(403).json({ error: "Forbidden" }); return;
    }

    const KEY = cfg.anthropic?.api_key || process.env.ANTHROPIC_API_KEY;
    if (!KEY) { res.status(500).json({ error: "No API key configured" }); return; }

    const subject = (req.body?.subject || "English_101");
    functions.logger.info("INTELLIGENCE_UPDATE_START", { subject });

    try {
      const prompt = `You are a CUET UG exam expert and content analyst with deep knowledge of NTA examination patterns.

Analyse the NTA CUET UG ${subject.replace("_", " ")} examination papers from 2022 to 2025 and produce a structured intelligence document.

Your output must be a JSON object with this exact structure:
{
  "subject": "${subject}",
  "analysisYear": 2025,
  "keyTrends": [
    "Concise trend statement 1 — specific, actionable, with year evidence",
    "Concise trend statement 2",
    ...up to 10 trends
  ],
  "topicInsights": {
    "TopicName": {
      "recentTrend": "What changed in 2024-25 vs 2022-23",
      "questionTypeFrequency": {"type": "percentage"},
      "avoidPatterns": ["pattern to avoid"],
      "emphasise": ["pattern to emphasise"],
      "difficultyLevel": "easy|moderate|challenging"
    }
  },
  "passageThemeTrends": {
    "emerging": ["new themes appearing in 2024-2025 papers"],
    "recurring": ["themes that have appeared 3+ times across papers"],
    "declining": ["themes that were common before 2023 but less frequent now"]
  },
  "vocabularyTrends": {
    "frequentWordTypes": ["academic", "literary", "technical"],
    "ceferLevel": "B2-C1",
    "noteworthy": "Any specific vocabulary pattern worth noting"
  },
  "difficultyTrend": "Is the paper getting harder, easier, or stable? Evidence?",
  "qualityBenchmarks": [
    "Specific quality standard derived from official paper analysis"
  ],
  "updatedAt": "${new Date().toISOString()}"
}

Be specific. Cite exam year evidence where possible. Focus on patterns that directly help generate better-aligned questions.
Return ONLY the JSON object. Begin with { — nothing before it.`;

      const r = await axios.post(
        "https://api.anthropic.com/v1/messages",
        {
          model: "claude-sonnet-4-6",
          max_tokens: 2000,
          messages: [{ role: "user", content: prompt }],
        },
        {
          headers: { "Content-Type": "application/json", "x-api-key": KEY, "anthropic-version": "2023-06-01" },
          timeout: 100000,
        }
      );

      const rawText  = r.data?.content?.[0]?.text || "";
      const newIntel = extractJSON(rawText);

      // Store in Firestore — admin dashboard reads this, health check monitors it
      const docRef = await db.collection("cuetIntelligence").add({
        subject,
        intelligence: newIntel,
        version:      `${subject}_${new Date().getFullYear()}_${Date.now()}`,
        generatedAt:  admin.firestore.FieldValue.serverTimestamp(),
        model:        "claude-sonnet-4-6",
      });

      // Prune — keep last 5 per subject
      const old = await db.collection("cuetIntelligence")
        .where("subject", "==", subject)
        .orderBy("generatedAt", "desc")
        .offset(5).limit(20).get();
      if (!old.empty) {
        const batch = db.batch();
        old.docs.forEach(d => batch.delete(d.ref));
        await batch.commit();
      }

      functions.logger.info("INTELLIGENCE_UPDATE_COMPLETE", { subject, docId: docRef.id });
      res.status(200).json({
        message: "Intelligence updated successfully",
        subject,
        docId: docRef.id,
        preview: {
          keyTrends:        newIntel.keyTrends?.slice(0, 3),
          difficultyTrend:  newIntel.difficultyTrend,
          updatedAt:        newIntel.updatedAt,
        },
      });

    } catch (e) {
      functions.logger.error("INTELLIGENCE_UPDATE_FAILED", { error: e.message });
      res.status(500).json({ error: "Intelligence update failed: " + e.message });
    }
  });



// ─── returnTestCredit ────────────────────────────────────────────────────────
// Grace window: called when student exits a Mock exam within 60s with 0 answers.
// Decrements testsUsed by 1 so the accidental open doesn't consume a free test.
// Guards: only works for unlocked=false users (free tier), max 3 returns per day,
// cannot reduce testsUsed below 0.
exports.returnTestCredit = functions
  .runWith({ timeoutSeconds: 15, memory: "128MB" })
  .https.onRequest(async (req, res) => {
    setCORS(res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }
    if (req.method !== "POST")    { res.status(405).json({ error: "Method not allowed" }); return; }
    const decoded = await verifyToken(req, res); if (!decoded) return;
    const uid = decoded.uid;
    try {
      const snap = await db.collection("users").doc(uid).get();
      const ud   = snap.data() || {};
      // Only for free-tier users — paid users have no limit to protect
      if (ud.unlocked) { res.status(200).json({ returned: false, reason: "paid_user" }); return; }
      // Cannot go below 0
      if ((ud.testsUsed || 0) <= 0) { res.status(200).json({ returned: false, reason: "already_zero" }); return; }
      // Abuse guard: max 3 grace returns per day per user
      const today      = new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" });
      const todayKey   = `graceReturns.${today}`;
      const todayCount = (ud.graceReturns || {})[today] || 0;
      if (todayCount >= 3) {
        res.status(200).json({ returned: false, reason: "daily_grace_limit_reached" }); return;
      }
      await db.collection("users").doc(uid).set({
        testsUsed:    admin.firestore.FieldValue.increment(-1),
        [todayKey]:   admin.firestore.FieldValue.increment(1),
      }, { merge: true });
      functions.logger.info("TEST_CREDIT_RETURNED", { uid, previousCount: ud.testsUsed });
      res.status(200).json({ returned: true, newCount: Math.max(0, (ud.testsUsed || 1) - 1) });
    } catch (e) {
      functions.logger.error("RETURN_CREDIT_FAILED", { uid, error: e.message });
      res.status(500).json({ error: "Could not return credit" });
    }
  });

// ─── grantAdminClaim ─────────────────────────────────────────────────────────
// One-time setup: grants admin:true custom claim to a Firebase UID.
// Call once for each admin account — then Firestore rules use the claim, not emails.
// Protected by admin key. Usage: POST { "uid": "FIREBASE_UID" }
exports.grantAdminClaim = functions
  .runWith({ timeoutSeconds: 30, memory: "128MB" })
  .https.onRequest(async (req, res) => {
    setCORS(res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }
    const adminKey    = req.body?.adminKey || req.headers["x-admin-key"] || "";
    const cfg         = functions.config();
    const expectedKey = cfg.admin?.key || process.env.ADMIN_KEY || "";
    if (!adminKey || adminKey !== expectedKey) {
      res.status(403).json({ error: "Forbidden" }); return;
    }
    const { uid } = req.body || {};
    if (!uid) { res.status(400).json({ error: "uid required" }); return; }
    try {
      await admin.auth().setCustomUserClaims(uid, { admin: true });
      functions.logger.info("ADMIN_CLAIM_GRANTED", { uid });
      res.status(200).json({ success: true, uid, claim: { admin: true } });
    } catch (e) {
      functions.logger.error("ADMIN_CLAIM_FAILED", { uid, error: e.message });
      res.status(500).json({ error: e.message });
    }
  });

// ─── 8. getCacheStatus ───────────────────────────────────────────────────────
// Lightweight read-only status check — no generation, responds in < 2s
exports.getCacheStatus = functions
  .runWith({ timeoutSeconds: 10, memory: "128MB" })
  .https.onRequest(async (req, res) => {
    setCORS(res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }
    const adminKey    = req.body?.adminKey || req.headers["x-admin-key"] || "";
    const cfg         = functions.config();
    const expectedKey = cfg.admin?.key || process.env.ADMIN_KEY || "";
    if (!adminKey || adminKey !== expectedKey) {
      res.status(403).json({ error: "Forbidden" }); return;
    }
    try {
      const cutoff = new Date(Date.now() - CACHE_TTL_MS);
      const status = {};
      for (const mode of MODES) {
        const snap  = await db.collection("questionCache").where("mode", "==", mode).get();
        const fresh = snap.docs.filter(d => d.data().createdAt?.toDate() > cutoff);
        status[mode] = { current: fresh.length, total: CACHE_SIZE, needed: Math.max(0, CACHE_SIZE - fresh.length) };
      }
      res.status(200).json({ status, checkedAt: new Date().toISOString() });
    } catch(e) {
      res.status(500).json({ error: e.message });
    }
  });

// ─── 9. platformHealthCheck ──────────────────────────────────────────────────
// Daily automated health check for all platform subsystems.
// Auto-fixes: cache fills if below threshold.
// All other issues: flagged only — nothing deleted or changed without admin approval.
// Stores result in Firestore healthChecks collection.
// Triggered by: GitHub Actions cron (6 AM IST daily) + admin dashboard "Run Now" button.
exports.platformHealthCheck = functions
  .runWith({ timeoutSeconds: 120, memory: "256MB" })
  .https.onRequest(async (req, res) => {
    setCORS(res);
    if (req.method === "OPTIONS") { res.status(204).send(""); return; }

    const adminKey    = req.body?.adminKey || req.headers["x-admin-key"] || "";
    const cfg         = functions.config();
    const expectedKey = cfg.admin?.key || process.env.ADMIN_KEY || "";
    if (!adminKey || adminKey !== expectedKey) {
      res.status(403).json({ error: "Forbidden" }); return;
    }

    const startedAt = new Date().toISOString();
    const checks    = {};
    const autoFixed = [];
    const warnings  = [];

    // ── CHECK 1: Cache health ─────────────────────────────────────────────
    try {
      const cutoff = new Date(Date.now() - CACHE_TTL_MS);
      const AUTO_FILL_THRESHOLD = 30; // below this → auto-trigger fill

      for (const mode of MODES) {
        const snap  = await db.collection("questionCache").where("mode", "==", mode).get();
        const fresh = snap.docs.filter(d => d.data().createdAt?.toDate() > cutoff);
        const count = fresh.length;
        const pct   = Math.round((count / CACHE_SIZE) * 100);

        // Detect substandard sets (wrong questionCount) — flag only, never delete
        const REQUIRED_Q    = mode === "Mock" ? 50 : 15;
        const substandard   = fresh.filter(d => {
          const qc = d.data().questionCount || (d.data().questions?.length ?? 0);
          return qc !== REQUIRED_Q;
        });

        const status = count >= 50 ? "healthy" : count >= 30 ? "warning" : "critical";
        checks[`cache_${mode}`] = {
          status, count, total: CACHE_SIZE, pct,
          substandard: substandard.length,
          substandardIds: substandard.map(d => d.id),
          message: `${count}/${CACHE_SIZE} sets fresh (${pct}%)${substandard.length > 0 ? ` · ${substandard.length} substandard sets flagged (not deleted — review before removing)` : ""}`,
        };

        // Auto-fix: cache below threshold → trigger fill (safe, additive only)
        if (count < AUTO_FILL_THRESHOLD) {
          const KEY = cfg.anthropic?.api_key || process.env.ANTHROPIC_API_KEY;
          if (KEY) {
            functions.logger.info("HEALTH_AUTO_FIX", { action: "triggerCacheWarm", mode, reason: `cache at ${count}/${CACHE_SIZE}` });
            // Fire-and-forget — health check responds immediately, fill runs in background
            db.collection("healthAutoFix").add({
              action: "cache_fill_triggered",
              mode,
              triggerReason: `cache_${status}:${count}/${CACHE_SIZE}`,
              triggeredAt: admin.firestore.FieldValue.serverTimestamp(),
            }).catch(() => {});
            autoFixed.push(`${mode} cache fill triggered automatically (was ${count}/${CACHE_SIZE})`);
            checks[`cache_${mode}`].autoFix = "cache_fill_triggered";
          }
        }
        if (substandard.length > 0) {
          warnings.push(`${substandard.length} ${mode} cache set(s) have wrong question count — review and manually delete if needed`);
        }
      }
    } catch (e) {
      checks.cache = { status: "error", message: e.message };
    }

    // ── CHECK 2: Firestore collections reachable ───────────────────────────
    const collections = ["users", "tests", "payments", "questionCache", "feedback", "ratings", "presence"];
    for (const col of collections) {
      try {
        const snap = await db.collection(col).limit(1).get();
        checks[`firestore_${col}`] = { status: "healthy", message: `${col} readable (${snap.size} doc sampled)` };
      } catch (e) {
        checks[`firestore_${col}`] = { status: "error", message: `${col} unreachable: ${e.message}` };
        warnings.push(`Firestore collection '${col}' is not readable`);
      }
    }

    // ── CHECK 3: Environment config presence ──────────────────────────────
    try {
      const cfgCheck = {
        anthropic_key:    !!(cfg.anthropic?.api_key  || process.env.ANTHROPIC_API_KEY),
        razorpay_key_id:  !!(cfg.razorpay?.key_id    || process.env.RAZORPAY_KEY_ID),
        razorpay_secret:  !!(cfg.razorpay?.secret    || process.env.RAZORPAY_SECRET),
        admin_key:        !!(cfg.admin?.key           || process.env.ADMIN_KEY),
      };
      const missing = Object.entries(cfgCheck).filter(([,v]) => !v).map(([k]) => k);
      checks.config = {
        status: missing.length === 0 ? "healthy" : "critical",
        present: Object.entries(cfgCheck).filter(([,v]) => v).map(([k]) => k),
        missing,
        message: missing.length === 0 ? "All secrets present" : `Missing: ${missing.join(", ")}`,
      };
      if (missing.length > 0) warnings.push(`Missing config keys: ${missing.join(", ")}`);
    } catch (e) {
      checks.config = { status: "error", message: e.message };
    }

    // ── CHECK 4: Firestore user doc health ────────────────────────────────
    try {
      const usersSnap  = await db.collection("users").get();
      const totalUsers = usersSnap.size;
      const paid       = usersSnap.docs.filter(d => d.data().unlocked === true).length;
      const noDoc      = 0; // placeholder — can't check uid-only users easily
      checks.users = {
        status: "healthy",
        total: totalUsers, paid,
        conversionPct: totalUsers > 0 ? Math.round((paid / totalUsers) * 100) : 0,
        message: `${totalUsers} users · ${paid} paid · ${totalUsers > 0 ? Math.round((paid / totalUsers) * 100) : 0}% conversion`,
      };
    } catch (e) {
      checks.users = { status: "error", message: e.message };
    }

    // ── CHECK 5: Last nightly cache warm (did it run recently?) ───────────
    try {
      const oneDayAgo  = new Date(Date.now() - 25 * 60 * 60 * 1000); // 25h window
      const cacheSnap  = await db.collection("questionCache")
        .orderBy("createdAt", "desc").limit(1).get();
      if (!cacheSnap.empty) {
        const lastCreated = cacheSnap.docs[0].data().createdAt?.toDate();
        const recentFill  = lastCreated && lastCreated > oneDayAgo;
        checks.nightly_cron = {
          status: recentFill ? "healthy" : "warning",
          lastCacheSet: lastCreated?.toISOString() || "unknown",
          message: recentFill
            ? `Cache was filled recently (${lastCreated?.toLocaleString("en-IN")})`
            : "No cache sets created in the last 25 hours — nightly cron may have missed",
        };
        if (!recentFill) warnings.push("Nightly cache fill may have missed — no new sets in 25 hours");
      } else {
        checks.nightly_cron = { status: "warning", message: "No cache sets found — cache appears empty" };
      }
    } catch (e) {
      checks.nightly_cron = { status: "error", message: e.message };
    }

    // ── Overall health score ──────────────────────────────────────────────
    const allStatuses  = Object.values(checks).map(c => c.status);
    const hasCritical  = allStatuses.includes("critical") || allStatuses.includes("error");
    const hasWarning   = allStatuses.includes("warning");
    const overallStatus = hasCritical ? "critical" : hasWarning ? "warning" : "healthy";

    const result = {
      overallStatus,
      checks,
      autoFixed,
      warnings,
      startedAt,
      completedAt: new Date().toISOString(),
      durationMs: Date.now() - new Date(startedAt).getTime(),
    };

    // Store in Firestore — admin dashboard reads this
    try {
      await db.collection("healthChecks").add({
        ...result,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
      });
      // Keep only last 30 health check records — clean up older ones
      const old = await db.collection("healthChecks").orderBy("createdAt", "desc").offset(30).limit(100).get();
      if (!old.empty) {
        const batch = db.batch();
        old.docs.forEach(d => batch.delete(d.ref));
        await batch.commit();
      }
    } catch (e) {
      functions.logger.warn("HEALTH_STORE_FAILED", { error: e.message });
    }

    functions.logger.info("HEALTH_CHECK_COMPLETE", { overallStatus, warnings: warnings.length, autoFixed: autoFixed.length });
    res.status(200).json(result);
  });


// ─── 9. platformHealthCheck ──────────────────────────────────────────────────
// Daily automated health check for all platform subsystems.
// Auto-fixes: cache fills if below threshold (safe, additive only).